const f=()=>{
    try {
        let a=0;    
        console.log(program);
        console.log("Program run successfully.");
        return;    
    } catch (error) {
        console.log("This is an error");
        console.log(p)
    }
    finally{
        console.log("I am a good boy.");
        //closed the file
        //exit the loop
        //write the log file
    }
    }
    f()